/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppThemesRouteImport } from './routes/_app/themes'
import { Route as AppWordsRouteImport } from './routes/_app/words'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiArchiveRouteImport } from './routes/api/archive'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiPreferencesRouteImport } from './routes/api/preferences'
import { Route as ApiRealtimeRouteImport } from './routes/api/realtime'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiArchiveDeleteAllRouteImport } from './routes/api/archive/delete-all'
import { Route as ApiArchiveImportRouteImport } from './routes/api/archive/import'
import { Route as ApiSessionsDeleteRouteImport } from './routes/api/sessions/delete'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppThemesRoute = AppThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AppRoute,
} as any)
const AppWordsRoute = AppWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => AppRoute,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveRoute = ApiArchiveRouteImport.update({
  id: '/api/archive',
  path: '/api/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesRoute = ApiPreferencesRouteImport.update({
  id: '/api/preferences',
  path: '/api/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveDeleteAllRoute = ApiArchiveDeleteAllRouteImport.update({
  id: '/delete-all',
  path: '/delete-all',
  getParentRoute: () => ApiArchiveRoute,
} as any)
const ApiArchiveImportRoute = ApiArchiveImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiArchiveRoute,
} as any)
const ApiSessionsDeleteRoute = ApiSessionsDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ApiSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof AppOnboardingRoute
  '/themes': typeof AppThemesRoute
  '/words': typeof AppWordsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/archive': typeof ApiArchiveRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/session': typeof ApiSessionRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/archive/delete-all': typeof ApiArchiveDeleteAllRoute
  '/api/archive/import': typeof ApiArchiveImportRoute
  '/api/sessions/delete': typeof ApiSessionsDeleteRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof AppOnboardingRoute
  '/themes': typeof AppThemesRoute
  '/words': typeof AppWordsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/archive': typeof ApiArchiveRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/session': typeof ApiSessionRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/': typeof AppIndexRoute
  '/api/archive/delete-all': typeof ApiArchiveDeleteAllRoute
  '/api/archive/import': typeof ApiArchiveImportRoute
  '/api/sessions/delete': typeof ApiSessionsDeleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/themes': typeof AppThemesRoute
  '/_app/words': typeof AppWordsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/archive': typeof ApiArchiveRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/session': typeof ApiSessionRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/api/archive/delete-all': typeof ApiArchiveDeleteAllRoute
  '/api/archive/import': typeof ApiArchiveImportRoute
  '/api/sessions/delete': typeof ApiSessionsDeleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/themes'
    | '/words'
    | '/api/ai'
    | '/api/archive'
    | '/api/login'
    | '/api/logout'
    | '/api/preferences'
    | '/api/realtime'
    | '/api/session'
    | '/api/sessions'
    | '/api/archive/delete-all'
    | '/api/archive/import'
    | '/api/sessions/delete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/themes'
    | '/words'
    | '/api/ai'
    | '/api/archive'
    | '/api/login'
    | '/api/logout'
    | '/api/preferences'
    | '/api/realtime'
    | '/api/session'
    | '/api/sessions'
    | '/'
    | '/api/archive/delete-all'
    | '/api/archive/import'
    | '/api/sessions/delete'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/onboarding'
    | '/_app/themes'
    | '/_app/words'
    | '/api/ai'
    | '/api/archive'
    | '/api/login'
    | '/api/logout'
    | '/api/preferences'
    | '/api/realtime'
    | '/api/session'
    | '/api/sessions'
    | '/_app/'
    | '/api/archive/delete-all'
    | '/api/archive/import'
    | '/api/sessions/delete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiArchiveRoute: typeof ApiArchiveRouteWithChildren
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiPreferencesRoute: typeof ApiPreferencesRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/themes': {
      id: '/_app/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof AppThemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/words': {
      id: '/_app/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof AppWordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive': {
      id: '/api/archive'
      path: '/api/archive'
      fullPath: '/api/archive'
      preLoaderRoute: typeof ApiArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences': {
      id: '/api/preferences'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive/delete-all': {
      id: '/api/archive/delete-all'
      path: '/delete-all'
      fullPath: '/api/archive/delete-all'
      preLoaderRoute: typeof ApiArchiveDeleteAllRouteImport
      parentRoute: typeof ApiArchiveRoute
    }
    '/api/archive/import': {
      id: '/api/archive/import'
      path: '/import'
      fullPath: '/api/archive/import'
      preLoaderRoute: typeof ApiArchiveImportRouteImport
      parentRoute: typeof ApiArchiveRoute
    }
    '/api/sessions/delete': {
      id: '/api/sessions/delete'
      path: '/delete'
      fullPath: '/api/sessions/delete'
      preLoaderRoute: typeof ApiSessionsDeleteRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
  }
}

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppThemesRoute: typeof AppThemesRoute
  AppWordsRoute: typeof AppWordsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppThemesRoute: AppThemesRoute,
  AppWordsRoute: AppWordsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiArchiveRouteChildren {
  ApiArchiveDeleteAllRoute: typeof ApiArchiveDeleteAllRoute
  ApiArchiveImportRoute: typeof ApiArchiveImportRoute
}

const ApiArchiveRouteChildren: ApiArchiveRouteChildren = {
  ApiArchiveDeleteAllRoute: ApiArchiveDeleteAllRoute,
  ApiArchiveImportRoute: ApiArchiveImportRoute,
}

const ApiArchiveRouteWithChildren = ApiArchiveRoute._addFileChildren(
  ApiArchiveRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsDeleteRoute: typeof ApiSessionsDeleteRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsDeleteRoute: ApiSessionsDeleteRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAiRoute: ApiAiRoute,
  ApiArchiveRoute: ApiArchiveRouteWithChildren,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiPreferencesRoute: ApiPreferencesRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiSessionRoute: ApiSessionRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
